SYSTEM:
    RNG_SEED: 42

MODEL:
    FILENAME: clipnet               # net/models/ file name
    NET: CLIPNet                    # class name in FILENAME
    EMB_SIZE: 768                   # for the largest model variant
    NUM_CLASSES: 10                 # number of output classes
    CLIP_VARIANT: ViT-L/14@336px    # the largest variant

LOSS: 
    TYPE: [CrossEntropyLoss] 
    WEIGHTS: [1.0]

DATASET:
    TRAIN: cifar10
    VAL: cifar10
    TEST: svhn
    SELECTED_LABELS: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]    # which labels from mnist are known classes
    TRAIN_LABEL_NAMES: [plane, car, bird, cat, deer, dog, frog, horse, ship, truck]   # class names
    AUGMENT: CLIPAugmentation

INPUT:
    BATCH_SIZE: 128 
    NUM_CHANNELS: 3
    IMG_SZ: 336      # for the largest model variant
    RGB: true

EXPERIMENT:
    EPOCHS: 1
    SKIP_EPOCHS: true
    EVAL_INTERVAL: 100

OPTIMIZER:
    METHOD: "adamw"
    LR: 0.001
    SCHEDULER: "cosine"

